spring.application.name=job_portal

# Database Configuration (Using H2 for simplicity, switch to MySQL if needed)
spring.datasource.url=jdbc:h2:mem:jobtrackrdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=kkrega
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
